r"""
     _____                        __  __           _      _ 
    |  __ \                      |  \/  |         | |    | |
    | |__) |_ _ _ __   ___ _ __  | \  / | ___   __| | ___| |
    |  ___/ _` | '_ \ / _ \ '__| | |\/| |/ _ \ / _` |/ _ \ |
    | |  | (_| | |_) |  __/ |    | |  | | (_) | (_| |  __/ |
    |_|   \__,_| .__/ \___|_|    |_|  |_|\___/ \__,_|\___|_|
                | |                                          
                |_|                         

    A simple rule-based model to generate realistical newspapers' pages for the training of the YOLO-Layout model.
"""
# This code is generated by ChatGPT
import os
import tkinter as tk
from tkinter import filedialog, messagebox
from PIL import Image, ImageTk


LABELS = {
    0: "Header",
    1: "Section",
    2: "Section Title",
    3: "Column",
    4: "Banner",
    5: "Footer",
}

LABEL_COLORS = {
    0: "red",
    1: "green",
    2: "blue",
    3: "orange",
    4: "purple",
    5: "cyan",
}

"""
YOLO Annotation Tool
--------------------

A lightweight Tkinter-based annotation utility for creating
YOLO-format bounding box datasets.

Features:
- Multi-image annotation
- Zoom and pan
- Automatic YOLO save/load
- Undo/delete support
- Scalable bounding boxes
- Label management

Annotations are stored in standard YOLO format:
    class_id x_center y_center width height
"""

class YoloAnnotator:
    """
    Main application class for the YOLO annotation tool.

    Handles:
    - image loading
    - annotation rendering
    - zoom/pan interactions
    - YOLO save/load
    - label management
    - navigation between images
    """
    def __init__(self, root):
        self.root = root
        self.root.title("YOLO Annotation Tool")
        self.root.geometry("1600x900")

        # -----------------------------
        # State
        # -----------------------------
        self.image_paths = []
        self.current_index = 0

        self.image = None
        self.tk_image = None
        self.image_id = None

        self.scale = 1.0
        self.min_scale = 0.2
        self.max_scale = 5.0

        self.offset_x = 0
        self.offset_y = 0

        self.annotations = []
        self.selected_annotation = None

        self.current_label = 0

        self.start_x = None
        self.start_y = None
        self.temp_rect = None

        self.pan_start_x = None
        self.pan_start_y = None

        # -----------------------------
        # UI
        # -----------------------------
        self.build_ui()
        self.bind_events()

    # =========================================================
    # UI
    # =========================================================

    def build_ui(self):
        self.main_frame = tk.Frame(self.root)
        self.main_frame.pack(fill=tk.BOTH, expand=True)

        # ---------------------------------
        # Sidebar
        # ---------------------------------
        self.sidebar = tk.Frame(self.main_frame, width=220, bg="#2b2b2b")
        self.sidebar.pack(side=tk.LEFT, fill=tk.Y)

        title = tk.Label(
            self.sidebar,
            text="Labels",
            font=("Arial", 16, "bold"),
            fg="white",
            bg="#2b2b2b",
        )
        title.pack(pady=10)

        for label_id, label_name in LABELS.items():
            btn = tk.Button(
                self.sidebar,
                text=f"{label_id} - {label_name}",
                bg=LABEL_COLORS[label_id],
                fg="white",
                command=lambda l=label_id: self.set_label(l),
            )
            btn.pack(fill=tk.X, padx=10, pady=3)

        tk.Label(
            self.sidebar,
            text="",
            bg="#2b2b2b"
        ).pack(pady=10)

        self.current_label_text = tk.Label(
            self.sidebar,
            text=f"Current: {LABELS[self.current_label]}",
            bg="#2b2b2b",
            fg="white",
            font=("Arial", 12, "bold"),
        )
        self.current_label_text.pack(pady=5)

        open_btn = tk.Button(
            self.sidebar,
            text="Open Images",
            command=self.load_images,
        )
        open_btn.pack(fill=tk.X, padx=10, pady=10)

        prev_btn = tk.Button(
            self.sidebar,
            text="Previous",
            command=self.prev_image,
        )
        prev_btn.pack(fill=tk.X, padx=10, pady=5)

        next_btn = tk.Button(
            self.sidebar,
            text="Next",
            command=self.next_image,
        )
        next_btn.pack(fill=tk.X, padx=10, pady=5)

        save_btn = tk.Button(
            self.sidebar,
            text="Save Annotations",
            command=self.save_annotations,
        )
        save_btn.pack(fill=tk.X, padx=10, pady=5)

        undo_btn = tk.Button(
            self.sidebar,
            text="Undo",
            command=self.undo_annotation,
        )
        undo_btn.pack(fill=tk.X, padx=10, pady=5)

        delete_btn = tk.Button(
            self.sidebar,
            text="Delete Selected",
            command=self.delete_selected,
        )
        delete_btn.pack(fill=tk.X, padx=10, pady=5)

        self.info_label = tk.Label(
            self.sidebar,
            text="No image loaded",
            bg="#2b2b2b",
            fg="white",
            wraplength=180,
            justify=tk.LEFT,
        )
        self.info_label.pack(padx=10, pady=20)

        # ---------------------------------
        # Canvas Area
        # ---------------------------------
        self.canvas_frame = tk.Frame(self.main_frame)
        self.canvas_frame.pack(side=tk.RIGHT, fill=tk.BOTH, expand=True)

        self.canvas = tk.Canvas(self.canvas_frame, bg="black")
        self.canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

        self.v_scroll = tk.Scrollbar(
            self.canvas_frame,
            orient=tk.VERTICAL,
            command=self.canvas.yview,
        )
        self.v_scroll.pack(side=tk.RIGHT, fill=tk.Y)

        self.h_scroll = tk.Scrollbar(
            self.root,
            orient=tk.HORIZONTAL,
            command=self.canvas.xview,
        )
        self.h_scroll.pack(fill=tk.X)

        self.canvas.configure(
            yscrollcommand=self.v_scroll.set,
            xscrollcommand=self.h_scroll.set,
        )

    # =========================================================
    # Events
    # =========================================================

    def bind_events(self):
        self.canvas.bind("<ButtonPress-1>", self.start_draw)
        self.canvas.bind("<B1-Motion>", self.draw_box)
        self.canvas.bind("<ButtonRelease-1>", self.finish_draw)

        self.canvas.bind("<ButtonPress-3>", self.start_pan)
        self.canvas.bind("<B3-Motion>", self.pan_image)

        self.canvas.bind("<MouseWheel>", self.zoom)

        self.canvas.bind("<Button-1>", self.select_annotation, add="+")

        self.root.bind("<Delete>", lambda e: self.delete_selected())
        self.root.bind("<Control-z>", lambda e: self.undo_annotation())

        for i in range(6):
            self.root.bind(str(i), lambda e, idx=i: self.set_label(idx))

    # =========================================================
    # Image Loading
    # =========================================================

    def load_images(self):
        paths = filedialog.askopenfilenames(
            filetypes=[
                ("Images", "*.png *.jpg *.jpeg *.bmp"),
            ]
        )

        if not paths:
            return

        self.image_paths = list(paths)
        self.current_index = 0
        self.load_current_image()

    def load_current_image(self):
        if not self.image_paths:
            return

        path = self.image_paths[self.current_index]

        self.image = Image.open(path)

        self.scale = 1.0
        self.offset_x = 0
        self.offset_y = 0

        self.annotations = []
        self.selected_annotation = None

        self.load_annotations()

        self.render_image()

        self.info_label.config(
            text=(
                f"Image {self.current_index + 1}/{len(self.image_paths)}\n\n"
                f"{os.path.basename(path)}\n"
                f"{self.image.width}x{self.image.height}"
            )
        )

    # =========================================================
    # Rendering
    # =========================================================

    def render_image(self):
        self.canvas.delete("all")

        width = int(self.image.width * self.scale)
        height = int(self.image.height * self.scale)

        resized = self.image.resize((width, height))

        self.tk_image = ImageTk.PhotoImage(resized)

        self.image_id = self.canvas.create_image(
            self.offset_x,
            self.offset_y,
            anchor=tk.NW,
            image=self.tk_image,
        )

        self.canvas.config(
            scrollregion=(
                0,
                0,
                width + abs(self.offset_x),
                height + abs(self.offset_y),
            )
        )

        self.redraw_annotations()

    def redraw_annotations(self):
        for ann in self.annotations:
            x1 = ann["x1"] * self.scale + self.offset_x
            y1 = ann["y1"] * self.scale + self.offset_y
            x2 = ann["x2"] * self.scale + self.offset_x
            y2 = ann["y2"] * self.scale + self.offset_y

            color = LABEL_COLORS[ann["class_id"]]

            width = 4 if ann == self.selected_annotation else 2

            rect_id = self.canvas.create_rectangle(
                x1,
                y1,
                x2,
                y2,
                outline=color,
                width=width,
            )

            text_id = self.canvas.create_text(
                x1 + 5,
                y1 + 10,
                anchor=tk.NW,
                fill=color,
                text=LABELS[ann["class_id"]],
                font=("Arial", 12, "bold"),
            )

            ann["rect_id"] = rect_id
            ann["text_id"] = text_id
        
    # =========================================================
    # Coordinate Utilities
    # =========================================================

    def canvas_to_image(self, x, y):
        ix = (x - self.offset_x) / self.scale
        iy = (y - self.offset_y) / self.scale
        return ix, iy

    # =========================================================
    # Drawing
    # =========================================================

    def start_draw(self, event):
        self.start_x = event.x
        self.start_y = event.y

        self.temp_rect = self.canvas.create_rectangle(
            self.start_x,
            self.start_y,
            self.start_x,
            self.start_y,
            outline=LABEL_COLORS[self.current_label],
            width=2,
            dash=(6, 3),
        )

    def draw_box(self, event):
        if self.temp_rect:
            self.canvas.coords(
                self.temp_rect,
                self.start_x,
                self.start_y,
                event.x,
                event.y,
            )

            self.canvas.delete(("preview_box"))
            self.canvas.delete("preview_text")

            width = abs(event.x - self.start_x)
            height = abs(event.y - self.start_y)

            self.canvas.create_rectangle(
                self.start_x,
                self.start_y,
                event.x,
                event.y,
                outline=LABEL_COLORS[self.current_label],
                width=2,
                dash=(6, 3),
                tags="preview_box",
            )

            self.canvas.create_text(
                event.x + 10,
                event.y + 10,
                anchor=tk.NW,
                text=f"{LABELS[self.current_label]} | {int(width)}x{int(height)}",
                fill=LABEL_COLORS[self.current_label],
                font=("Arial", 10, "bold"),
                tags="preview_text",
            )

    def finish_draw(self, event):
        if not self.temp_rect:
            return

        ix1, iy1 = self.canvas_to_image(self.start_x, self.start_y)
        ix2, iy2 = self.canvas_to_image(event.x, event.y)

        if abs(ix2 - ix1) < 5 or abs(iy2 - iy1) < 5:
            self.canvas.delete(self.temp_rect)
            self.canvas.delete("preview_text")
            self.temp_rect = None
            return

        annotation = {
            "class_id": self.current_label,
            "x1": min(ix1, ix2),
            "y1": min(iy1, iy2),
            "x2": max(ix1, ix2),
            "y2": max(iy1, iy2),
        }

        self.annotations.append(annotation)

        self.canvas.delete(self.temp_rect)
        self.canvas.delete("preview_text")
        self.temp_rect = None

        self.render_image()

    # =========================================================
    # Selection
    # =========================================================

    def select_annotation(self, event):
        clicked = self.canvas.find_overlapping(
            event.x,
            event.y,
            event.x,
            event.y,
        )

        self.selected_annotation = None

        for ann in self.annotations:
            if ann.get("rect_id") in clicked:
                self.selected_annotation = ann
                break

        self.render_image()

    # =========================================================
    # Zoom / Pan
    # =========================================================

    def zoom(self, event):
        old_scale = self.scale

        if event.delta > 0:
            self.scale *= 1.1
        else:
            self.scale *= 0.9

        self.scale = max(self.min_scale, min(self.max_scale, self.scale))

        scale_factor = self.scale / old_scale

        self.offset_x = event.x - scale_factor * (event.x - self.offset_x)
        self.offset_y = event.y - scale_factor * (event.y - self.offset_y)

        self.render_image()

    def start_pan(self, event):
        self.pan_start_x = event.x
        self.pan_start_y = event.y

    def pan_image(self, event):
        dx = event.x - self.pan_start_x
        dy = event.y - self.pan_start_y

        self.offset_x += dx
        self.offset_y += dy

        self.pan_start_x = event.x
        self.pan_start_y = event.y

        self.render_image()

    def get_annotation_path(self):
        image_path = self.image_paths[self.current_index]
        base, _ = os.path.splitext(image_path)
        return base + ".txt"

    def save_annotations(self):
        if not self.image:
            return

        path = self.get_annotation_path()

        with open(path, "w") as f:
            for ann in self.annotations:
                x1 = ann["x1"]
                y1 = ann["y1"]
                x2 = ann["x2"]
                y2 = ann["y2"]

                x_center = ((x1 + x2) / 2) / self.image.width
                y_center = ((y1 + y2) / 2) / self.image.height
                width = abs(x2 - x1) / self.image.width
                height = abs(y2 - y1) / self.image.height

                line = (
                    f"{ann['class_id']} "
                    f"{x_center:.6f} "
                    f"{y_center:.6f} "
                    f"{width:.6f} "
                    f"{height:.6f}\n"
                )

                f.write(line)

        messagebox.showinfo("Saved", f"Annotations saved to:\n{path}")

    def load_annotations(self):
        path = self.get_annotation_path()

        if not os.path.exists(path):
            return

        with open(path, "r") as f:
            lines = f.readlines()

        for line in lines:
            parts = line.strip().split()

            if len(parts) != 5:
                continue

            class_id = int(parts[0])
            x_center = float(parts[1])
            y_center = float(parts[2])
            width = float(parts[3])
            height = float(parts[4])

            box_width = width * self.image.width
            box_height = height * self.image.height

            center_x = x_center * self.image.width
            center_y = y_center * self.image.height

            x1 = center_x - box_width / 2
            y1 = center_y - box_height / 2
            x2 = center_x + box_width / 2
            y2 = center_y + box_height / 2

            self.annotations.append({
                "class_id": class_id,
                "x1": x1,
                "y1": y1,
                "x2": x2,
                "y2": y2,
            })

    # =========================================================
    # Editing
    # =========================================================

    def undo_annotation(self):
        if self.annotations:
            self.annotations.pop()
            self.selected_annotation = None
            self.render_image()

    def delete_selected(self):
        if self.selected_annotation in self.annotations:
            self.annotations.remove(self.selected_annotation)
            self.selected_annotation = None
            self.render_image()

    # =========================================================
    # Navigation
    # =========================================================

    def next_image(self):
        if not self.image_paths:
            return

        self.save_annotations()

        if self.current_index < len(self.image_paths) - 1:
            self.current_index += 1
            self.load_current_image()

    def prev_image(self):
        if not self.image_paths:
            return

        self.save_annotations()

        if self.current_index > 0:
            self.current_index -= 1
            self.load_current_image()

    # =========================================================
    # Labels
    # =========================================================

    def set_label(self, label_id):
        self.current_label = label_id

        self.current_label_text.config(
            text=f"Current: {LABELS[label_id]}"
        )


# =============================================================
# Main
# =============================================================

if __name__ == "__main__":
    root = tk.Tk()
    app = YoloAnnotator(root)
    root.mainloop()
